server:
  port: 8084

spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  sql:
    init:
      data-locations: classpath:catalog.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
