server:
  port: 8085

spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
        
info:
  app:
    name: catalog-service
    description: Catalog service application for backend specialization exam.
      
