server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute 
          uri: http://localhost:8082/ 
          predicates:
            - Path=/movies/**
        - id: catalogRoute 
          uri: http://localhost:8084/
          predicates: 
            - Path=/catalogs/**

info:
  app:
    name: gateway-service
    description: Gateway service application for backend specialization exam.
